application: myimgur
version: 1
runtime: python
api_version: 1

inbound_services:
- mail

handlers:
- url: /static
  static_dir: static

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /_ah/mail/upload@(.*)
  script: mail_upload.py
  login: admin

